#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-AutoDB
version:      0.091
version_from: lib/Class/AutoDB.pm
installdirs:  site
requires:
    YAML:                          0
    Error:                         0.15
    Class::Singleton:              0
    Test::More:                    0.45
    Set::Scalar:                   0
    DBD::mysql:                    2.9002
    Class::WeakSingleton:          1.03
    Text::Abbrev:                  0
    Class::AutoClass:              0.09
    Test::Deep:                    0
    Storable:                      2.06
    IO::Scalar:                    2.104
    Data::Dumper:                  2.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
