---
abstract: 'Almost automatic object persistence coexisting with human-engineered database'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Carp: 1.2
  Class::AutoClass: 1.55
  Cwd: 3.4
  DBD::mysql: 4.024
  DBI: 1.628
  Data::Rmap: 0.62
  ExtUtils::CBuilder: 0
  Fcntl: 1.11
  File::Basename: 2.82
  File::Spec: 3.4
  File::Spec::Functions: 3.4
  FindBin: 1.5
  FreezeThaw: 0.5001
  Getopt::Long: 2.38
  Graph: 0.94
  Hash::AutoHash::Args: 1.16
  List::MoreUtils: 0.33
  List::Util: 1.23
  Module::Build: 0.4007
  SDBM_File: 1.09
  Scalar::Util: 1.23
  Storable: 2.3
  TAP::Harness: 3.28
  TAP::Parser::Aggregator: 3.28
  Test::Deep: 0.11
  Test::More: 0.98
  Test::Pod: 1.48
  Test::Pod::Content: v0.0.6
configure_requires:
  Cwd: 3.4
  Module::Build: 0.4007
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-AutoDB
provides:
  Class::AutoDB:
    file: lib/Class/AutoDB.pm
    version: 1.27_02
  Class::AutoDB::BaseTable:
    file: lib/Class/AutoDB/BaseTable.pm
    version: 0
  Class::AutoDB::Collection:
    file: lib/Class/AutoDB/Collection.pm
    version: 0
  Class::AutoDB::CollectionDiff:
    file: lib/Class/AutoDB/CollectionDiff.pm
    version: 0
  Class::AutoDB::Connect:
    file: lib/Class/AutoDB/Connect.pm
    version: 0
  Class::AutoDB::Cursor:
    file: lib/Class/AutoDB/Cursor.pm
    version: 0
  Class::AutoDB::Database:
    file: lib/Class/AutoDB/Database.pm
    version: 0
  Class::AutoDB::Dumper:
    file: lib/Class/AutoDB/Dumper.pm
    version: 0
  Class::AutoDB::Globals:
    file: lib/Class/AutoDB/Globals.pm
    version: 0
  Class::AutoDB::ListTable:
    file: lib/Class/AutoDB/ListTable.pm
    version: 0
  Class::AutoDB::Object:
    file: lib/Class/AutoDB/Object.pm
    version: 0
  Class::AutoDB::Oid:
    file: lib/Class/AutoDB/Oid.pm
    version: 0
  Class::AutoDB::OidDeleted:
    file: lib/Class/AutoDB/OidDeleted.pm
    version: 0
  Class::AutoDB::Registration:
    file: lib/Class/AutoDB/Registration.pm
    version: 0
  Class::AutoDB::Registry:
    file: lib/Class/AutoDB/Registry.pm
    version: 0
  Class::AutoDB::RegistryDiff:
    file: lib/Class/AutoDB/RegistryDiff.pm
    version: 0
  Class::AutoDB::RegistryVersion:
    file: lib/Class/AutoDB/RegistryVersion.pm
    version: 0
  Class::AutoDB::Serialize:
    file: lib/Class/AutoDB/Serialize.pm
    version: 0
  Class::AutoDB::Table:
    file: lib/Class/AutoDB/Table.pm
    version: 0
recommends:
  Test::mysqld: 0.17
requires:
  Class::AutoClass: 1.55
  Class::Singleton: 1.4
  Cwd: 3.4
  DBD::mysql: 4.024
  DBI: 1.628
  Exporter: 5.68
  Fcntl: 1.11
  Hash::AutoHash: 1.16
  Hash::AutoHash::Args: 1.17
  List::MoreUtils: 0.33
  List::Util: 1.32
  Storable: 2.3
  Text::Abbrev: 1.02
  Tie::ToObject: 0.03
  XSLoader: 0.15
resources:
  license: http://dev.perl.org/licenses/
version: 1.27_02
