---
abstract: 'Almost automatic object persistence coexisting with human-engineered database'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Carp: 0
  Class::AutoClass: 1.53
  Config: 0
  Cwd: 3.26
  DBD::mysql: 4.007
  DBI: 1.604
  Data::Rmap: 0.61
  Exporter: 5.58
  ExtUtils::CBuilder: 0.22
  File::Basename: 0
  File::Spec: 3.26
  File::Spec::Functions: 3.26
  FindBin: 0
  Getopt::Long: 2.13
  Hash::AutoHash::Args: 1.11
  List::MoreUtils: 0.09
  List::Util: 1.14
  SDBM_File: 0
  Scalar::Util: 1.01
  Storable: 2.16
  TAP::Harness: 3.12
  Test::Deep: 0.098
  Test::More: 0.88
configure_requires:
  Cwd: 3.26
  DBD::mysql: 4.007
  DBI: 1.604
  File::Spec: 3.26
  Module::Build: 0.36
  SDBM_File: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-AutoDB
provides:
  Class::AutoDB:
    file: lib/Class/AutoDB.pm
    version: 1.19_02
  Class::AutoDB::BaseTable:
    file: lib/Class/AutoDB/BaseTable.pm
  Class::AutoDB::Collection:
    file: lib/Class/AutoDB/Collection.pm
  Class::AutoDB::CollectionDiff:
    file: lib/Class/AutoDB/CollectionDiff.pm
  Class::AutoDB::Connect:
    file: lib/Class/AutoDB/Connect.pm
  Class::AutoDB::Cursor:
    file: lib/Class/AutoDB/Cursor.pm
  Class::AutoDB::Database:
    file: lib/Class/AutoDB/Database.pm
  Class::AutoDB::Dumper:
    file: lib/Class/AutoDB/Dumper.pm
  Class::AutoDB::Globals:
    file: lib/Class/AutoDB/Globals.pm
  Class::AutoDB::ListTable:
    file: lib/Class/AutoDB/ListTable.pm
  Class::AutoDB::Object:
    file: lib/Class/AutoDB/Object.pm
  Class::AutoDB::Oid:
    file: lib/Class/AutoDB/Oid.pm
  Class::AutoDB::OidDeleted:
    file: lib/Class/AutoDB/OidDeleted.pm
  Class::AutoDB::Registration:
    file: lib/Class/AutoDB/Registration.pm
  Class::AutoDB::Registry:
    file: lib/Class/AutoDB/Registry.pm
  Class::AutoDB::RegistryDiff:
    file: lib/Class/AutoDB/RegistryDiff.pm
  Class::AutoDB::RegistryVersion:
    file: lib/Class/AutoDB/RegistryVersion.pm
  Class::AutoDB::Serialize:
    file: lib/Class/AutoDB/Serialize.pm
  Class::AutoDB::Table:
    file: lib/Class/AutoDB/Table.pm
requires:
  Carp: 0
  Class::AutoClass: 1.54
  Class::Singleton: 1.04
  DBD::mysql: 4.007
  DBI: 1.604
  Hash::AutoHash::Args: 1.11
  Scalar::Util: 1.01
  Text::Abbrev: 1.01
  Tie::ToObject: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 1.19_02
